### PR TITLE
Updated labels to function

### PR DESCRIPTION
**Pull request by estraily-navisjon**
Switched all the labels to the function I made, except for the labels that are blank

### CODE REVIEW

**Comment by TristanDebrunner** [comment]
Just a clarity point, what you really did here was create the labels with your function, not update them.

**Comment by estraily-navisjon** [comment]
> Just a clarity point, what you really did here was create the labels with your function, not update them.

ok, so since I basically fundamentally changed their definition it is more a create than an update?

**Comment by TristanDebrunner** [comment]
bors cancel

**Comment by TristanDebrunner** [comment]
bors help

**Comment by TristanDebrunner** [comment]
> > Just a clarity point, what you really did here was create the labels with your function, not update them.
> 
> ok, so since I basically fundamentally changed their definition it is more a create than an update?

What you did was change how they're created. (A `let` statement is always creating a new object)

**Pull request merged**
